### ISSUE TITLE
About data splits

### ISSUE THREAD

**Issue by tomchen-ctj** [alibaba-mmai-research/CLIP-FSAR#1]
Hi, thank you for your great work!
Could you please release the data splits for Sthv2 and Kinetics?

**Comment by wangxiang1230** [comment]
> Hi, thank you for your great work! Could you please release the data splits for Sthv2 and Kinetics?

Hi, sorry for the late reply. For dataset splits, you can refer to our [HyRSM code](https://github.com/alibaba-mmai-research/HyRSM/tree/main/configs/projects/hyrsm), which contains the txt split files. Thanks.

**Comment by ssp-seven** [comment]
How do I split it?
